<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Quickview
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
$helper = $block->getHelper();
$btnTextColor = $helper->getBtnTextColor();
$baseUrl = $helper->getBaseUrl();
$buttonText = $helper->getButtonText();
$btnBackground = $helper->getBtnBackground();
list($r, $g, $b) = sscanf($btnBackground, "%02x%02x%02x");
$productUrl = $helper->getUrl();
$buttonText = $helper->getButtonText();
$isEnabled = $helper->enabled();
$productItemInfo = $helper->getProductItemInfo();
$productImageWrapper = $helper->getProductImageWrapper();
?>

<style>
    a.mavenbird-quickview{
        color: #<?= /*@noEscape*/ $btnTextColor; ?>;
        background-color: rgba(<?= /*@noEscape*/ "$r , $g , $b"; ?>,0.6);
    }
    a.mavenbird-quickview {
        position: absolute;
        display: block;
        bottom: 0px;
        padding: 3px 10px;
        margin-left: auto;
        margin-right: auto;
        left: 0;
        right: 0;
        }
    .product-item .product-item-info:hover .mavenbird-quickview{
        display: block !important;
        position: absolute !important;
        bottom: 0px !important;
        left: 0px !important;
        margin: 0;
        z-index: 99999999999999 !important;
        width: 100% !important;
        padding: 10px 0 10px 0;
        text-align: center !important;
        font-size: 14px !important;
        text-decoration: none !important;
    }

    .product-item .product-item-info:hover .mavenbird-quickview{
        display: block !important;
        position: absolute !important;
        bottom: 0px !important;
        left: 0px !important;
        margin: 0;
        z-index: 99999999999999 !important;
        width: 100% !important;
        padding: 10px 0 10px 0;
        text-align: center !important;
        font-size: 14px !important;
        text-decoration: none !important;
    }
    .product-item .mavenbird-quickview {display: none !important}
    #shopping-cart-table .mavenbird-quickview {display: none !important}
    .products-related .product-item-info:hover .mavenbird-quickview, .products-upsell .product-item-info:hover .mavenbird-quickview {display: none !important}
</style>
<script type="text/x-magento-init">
    {
        "*": {
            "Mavenbird_Quickview/js/mavenbird_config": {
                "productUrl": "<?= /*@noEscape*/ $productUrl; ?>",
                "buttonText": "<?= /*@noEscape*/ $buttonText; ?>",
                "isEnabled": "<?= /*@noEscape*/ $isEnabled; ?>",
                "baseUrl": "<?= /*@noEscape*/ $baseUrl; ?>",
                "productItemInfo": "<?= /*@noEscape*/ $productItemInfo; ?>",
                "productImageWrapper": "<?= /*@noEscape*/ $productImageWrapper; ?>"
            }
        }
    }
</script>
