<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Quickview
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php $product = $block->getProduct();
?>
<div id="ajax-goto">
    <a class="goto-product" href="<?= /*@noEscape*/ $product->getUrlModel()->getUrl($product);?>">
        <span><?= /*@noEscape*/ __('Go to Product'); ?></span>
    </a>
</div>
