<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Quickview
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /*@noEscape*/ __('Qty') ?></span></label>
                    <div class="control">
                        <input 
                            type="number"
                            name="qty"
                            id="qty"
                            maxlength="12"
                            value="<?= /*@noEscape*/ $block->getProductDefaultQty() * 1 ?>"
                            title="<?= /*@noEscape*/ __('Qty') ?>" class="input-text qty"
                            data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button
                    type="submit"
                    title="<?= /*@noEscape*/ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                    <span><?= /*@noEscape*/ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "mavenbird_quickview/catalog_product": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
    {
        ".actions": {
            "Mavenbird_Quickview/js/mavenbird_tocart": {
            }
        }
    }
    </script>
<?php endif; ?>
